version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
    volumes:
      - ./minecraftData:/data
    restart: unless-stopped
    networks:
      - minecraft_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: unless-stopped
    command: start --all --config /etc/ngrok/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - "4040:4040"
    networks:
      - minecraft_network

networks:
  minecraft_network:
    driver: bridge
